PhotoApp.Web/Controllers/TreeviewController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using PhotoApp.Utils;
using PhotoApp.Utils.Models;
using PhotoApp.Web.Authentification.Utils;

namespace PhotoApp.Web.Controllers
{
    public class TreeviewController : Controller
    {
        private readonly ILogger<TreeviewController> _logger;
        private readonly TreeviewViewModel _treeviewModel;

        private const string ApiAlbums = "api/Albums";
        private const string ApiPhotos = "api/Photos";
        private const string ApiGetRefreshToken = "api/Auth/GetRefreshedToken";
        private readonly int _cookieExpiration;
        private readonly string Baseurl = null;

        public TreeviewController(TreeviewViewModel treeviewModel,
            ILogger<TreeviewController> logger,
            IConfiguration configuration)
        {
            _treeviewModel = treeviewModel;
            _logger = logger;

            _cookieExpiration = configuration.GetValue<int>("CookieExpiration");
            Baseurl = configuration.GetValue<string>("UrlWebAPi");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var token = HttpContext.Request.Cookies["X-Access-Token"];
            if (token == null)
                return Redirect("../Home/Index");

            if (JWTService.HasTokenExpired(token, TimeSpan.FromSeconds(30)))
            {
                string tokenResult = null;
                try
                {
                    tokenResult =
                        await JWTService.RequestForNewToken(Request.Cookies["X-Access-User"], Baseurl, ApiGetRefreshToken);
                }
                catch (HttpRequestException e)
                {
                    ViewBag.ErrorMessage = $"Web API {Baseurl}/{ApiGetRefreshToken} is unavailable";
                    return View("Index");
                }

                if (!string.IsNullOrEmpty(tokenResult))
                {
                    //delete the old variable cookie
                    Response.Cookies.Delete("X-Access-Token");
                    Response.Cookies.Append("X-Access-Token", tokenResult,
                        new CookieOptions()
                        {
                            Expires = DateTime.Now.AddDays(_cookieExpiration),
                            HttpOnly = true,
                            SameSite = SameSiteMode.Strict
                        });
                }
                else
                {
                    HttpContext.Session.SetString("IsLogged", false.ToString());
                    View("Index");
                }
            }

            List<AlbumModelDto> albums;
            try
            {
                albums = await GetAllAlbums();
            }
            catch (HttpRequestException e)
            {
                ViewBag.ErrorMessage = $"Web API {Baseurl}/{ApiAlbums} is unavailable";
                return View("Index");
            }

            if (albums == null)
                return NoContent();

            var treeviewStructure = TreeviewUtils.FindRootNode(albums);
            if (treeviewStructure != null)
            {
                foreach (var item in albums)
                {
                    if (item.Path.Contains("\\"))
                    {
                        string[] splittedValues = item.Path.Split("\\", StringSplitOptions.RemoveEmptyEntries);
                        if (splittedValues.Length != 0)
                        {
                            TreeviewUtils.FillTree(ref treeviewStructure, 
                                item.Id.ToString(), 
                                item.NbPhotos,
                                splittedValues.Where((string x) => x != treeviewStructure.Header).ToList());
                        }
                    }
                }
            }

            _treeviewModel.AlbumsFolders = treeviewStructure;
            return View(_treeviewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetFileFromPath(string filePath, string albumid)
        {
            //validate your model    
            if (string.IsNullOrWhiteSpace(filePath) || !ModelState.IsValid)
            {
                return View("Index");
            }

            var token = HttpContext.Request.Headers["Authorization"].FirstOrDefault();
            if (JWTService.HasTokenExpired(token, TimeSpan.FromSeconds(30)))
            {
                var tokenResult = await JWTService.RequestForNewToken(Request.Cookies["X-Access-User"], Baseurl, ApiGetRefreshToken);
                if (!string.IsNullOrEmpty(tokenResult))
                {
                    token = "Bearer" + " " + tokenResult;
                    //delete the old variable cookie
                    Response.Cookies.Delete("X-Access-Token");
                    Response.Cookies.Append("X-Access-Token", tokenResult,
                        new CookieOptions() { Expires = DateTime.Now.AddDays(_cookieExpiration), HttpOnly = true, SameSite = SameSiteMode.Strict });
                }
                else
                {
                    HttpContext.Session.SetString("IsLogged", false.ToString());
                    return View("Index");
                }
            }

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + Request.Cookies["X-Access-Token"]);
                var request = $"{Baseurl}/{ApiPhotos}/GetThumbnailBigVersion?photoPath={filePath}&albumId={albumid}";
                var response = await client.GetAsync(request);
                if (response.IsSuccessStatusCode)
                {
                    using (HttpContent resContent = response.Content)
                    {
                        var jsonResponse = await resContent.ReadAsByteArrayAsync();
                        return File(jsonResponse, "image/png");
                    }
                }
            }
            return View("Index");
        }

        private async Task<List<AlbumModelDto>> GetAllAlbums()
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + Request.Cookies["X-Access-Token"]);

                var response = await client.GetAsync($"{Baseurl}/{ApiAlbums}");
                if (response.IsSuccessStatusCode)
                {
                    using (HttpContent resContent = response.Content)
                    {
                        var jsonResponse = await resContent.ReadAsStringAsync();
                        if (!string.IsNullOrEmpty(jsonResponse))
                        {
                            return JsonConvert.DeserializeObject<List<AlbumModelDto>>(jsonResponse);
                        }
                    }
                }
            }

            return null;
        }

        [HttpGet]
        public async Task<IActionResult> GetPhotosFromAlbum(string albumId, string pageNumber, string nbPhotosForAlbum)
        {
            var token = Request.Cookies["X-Access-Token"];
            if (token == null)
                return Redirect("../Home/Index");

            if (JWTService.HasTokenExpired(token, TimeSpan.FromSeconds(30)))
            {
                string tokenResult = null;
                try
                {
                    tokenResult =
                        await JWTService.RequestForNewToken(Request.Cookies["X-Access-User"], Baseurl, ApiGetRefreshToken);
                }
                catch (HttpRequestException e)
                {
                    ViewBag.ErrorMessage = $"Web API {Baseurl}/{ApiGetRefreshToken} is unavailable";
                    return View("Index");
                }

                if (!string.IsNullOrEmpty(tokenResult))
                {
                    //delete the old variable cookie
                    Response.Cookies.Delete("X-Access-Token");
                    Response.Cookies.Append("X-Access-Token", tokenResult,
                        new CookieOptions()
                        {
                            Expires = DateTime.Now.AddDays(_cookieExpiration),
                            HttpOnly = true,
                            SameSite = SameSiteMode.Strict
                        });
                }
                else
                {
                    HttpContext.Session.SetString("IsLogged", false.ToString());
                    View("Index");
                }
            }

            PhotosModelDto photosModelDto;
            try
            {
                photosModelDto = await GetPhotosFromAlbumAsync(
                    Convert.ToInt32(albumId),
                    Convert.ToInt32(pageNumber),
                    Convert.ToInt32(nbPhotosForAlbum));
            }
            catch (HttpRequestException e)
            {
                ViewBag.ErrorMessage = $"Web API {Baseurl}/{ApiPhotos} is unavailable";
                return View("Index");
            }

            if (photosModelDto == null)
                return NoContent();

            _treeviewModel.PhotosModel = new PhotosModelDto(photosModelDto.ListPhotos);
            return PartialView("~/Views/Partial/PhotosList.cshtml", _treeviewModel.PhotosModel.ListPhotos);
        }


        private async Task<PhotosModelDto> GetPhotosFromAlbumAsync(int albumId, int pageNumber, int nbPhotoFromAlbum)
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + Request.Cookies["X-Access-Token"]);

PhotoApp.Web/Views/Treeview/Index.cshtml
@using PhotoApp.Utils
@model PhotoApp.Utils.Models.TreeviewViewModel
@section Scripts{

    <script type="text/javascript">
        $(function() {
            $("div#loading").hide();
        });

        $(function() {
            $('.tree li:has(ul)').addClass('parent_li');
            $('.tree li.parent_li > span').on('click',
                function(e) {
                    var children = $(this).parent('li.parent_li').find(' > ul > li');
                    if (children.is(":visible")) {
                        children.hide('fast');
                        $(this).find(' > i').addClass('fa-plus-square').removeClass('fa-minus-square');
                    } else {
                        children.show('fast');
                        $(this).find(' > i').addClass('fa-minus-square').removeClass('fa-plus-square');
                    }
                });
        });

        $(document).ready(function() {
/*            collapse all children at startup*/
            $(function() {
                var children = $('.tree li.parent_li > span').parent('li.parent_li').find(' > ul > li');
                if (children.is(":visible")) {
                    children.hide('fast');
                }
            });
        });

        $(".leaf").click(function() {
            albumId = $(this).attr("id");
            nbPhotosTotalForAlbumId = $(this).attr("itemprop");
            page = 1;
            if (albumId != previousAlbumId) {
                loadPhotosOnce(albumId);
            }
        });

        var page = 1,
            albumId = '',
            nbPhotosTotalForAlbumId = 0,
            previousAlbumId = '',
            inCallback = false;

        $("div#partial").scroll(function(event) {
            var element = event.target;
            if (Math.abs(element.scrollHeight - element.scrollTop - element.clientHeight) <= 3.0) {
                var nbPhotosDisplayed = $('.photoframe').length;
                if (nbPhotosDisplayed < nbPhotosTotalForAlbumId) {
                    loadPhotosOnScrollDown();
                }
            }
        });

        function loadPhotosOnce(leafAlbumId) {
            if (page > -1 && !inCallback) {
                inCallback = true;
                $("div#loading").show();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetPhotosFromAlbum", "Treeview")',
                    data: { albumId: leafAlbumId, pageNumber: page, nbPhotosForAlbum: nbPhotosTotalForAlbumId },
                    success: function(data, textstatus) {
                        if (data != '') {
                            if (albumId != previousAlbumId) {
                                $("div#partial").empty();
                            }
                            $("div#partial").append(data);
                        } else {
                            page = -1;
                        }

                        inCallback = false;
                        previousAlbumId = albumId;
                        $("div#loading").hide();
                    },
                    error: function(XMLHttpRequest, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
                });
            }
        }

        function loadPhotosOnScrollDown() {
            if (page > -1 && !inCallback) {
                inCallback = true;
                page++;
                $("div#loading").show();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetPhotosFromAlbum", "Treeview")',
                    data: { albumId: albumId, pageNumber: page, nbPhotosForAlbum: nbPhotosTotalForAlbumId },
                    success: function(data, textstatus) {
                        if (data != '') {
                            $("div#partial").append(data);
                        } else {
                            page = -1;
                        }

                        inCallback = false;
                        $("div#loading").hide();
                    },
                    error: function(XMLHttpRequest, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
                });
            }
        }

    </script>
}

<div style="display: block; width: 100%; height: 500px">
    <div style="width: 35%; float: left; display: inline-block; position: relative; border: 2px solid #94a0b4;">
        <div class="tree" style="height: 500px; overflow-y: auto;">
            @if (Model != null)
            {
                <ul id="folders">
                    <li>
                        <span><i class="fa fa-folder-open"></i>@Model.AlbumsFolders?.Header</span>
                        <li>
                            @{
                                TreeView(Model.AlbumsFolders?.Children);
                            }
                        </li>
                    </li>
                </ul>
            }
        </div>
    </div>
    <div style="width: 65%; float: left; display: inline-block; position: relative; border: 2px solid #94a0b4;">
        <div id="loading" class="loading-div">
            <img width="75" height="75" src='~/images/loading.svg'/>
        </div>
        <div id="partial" style="height: 500px; overflow-y: auto;">
            @if (Model?.PhotosModel != null)
            {
                @await Html.PartialAsync("~/Views/Partial/PhotosList.cshtml", Model.PhotosModel.ListPhotos)
            }
        </div>
    </div>
</div>

@functions
{
    void TreeView(IEnumerable<TreeviewUtils.AlbumFolder> albumsFolders)
    {
    @foreach (var albumFolder in albumsFolders)
    {
    @if (albumFolder.IsLeaf)
    {
        <ul>
            <li>
                <span itemprop="@albumFolder.NumberOfPhotos" class="leaf" id="@albumFolder.Id">@albumFolder.Header</span>
            </li>
        </ul>
    }
    else
    {
        <ul>
            <li>
                <span><i class="fa fa-folder-open"></i>@albumFolder.Header</span>
                @{ TreeView(albumFolder.Children);}
            </li>
        </ul>
    }
    }
    }
}